services:
  - type: web
    name: speech-coach
    runtime: docker
    rootDir: Projects/speech-coach
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
